In [ ]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/

In [ ]:
!ls "/content/drive/My Drive/Colab Notebooks/Adopt a Buddy/"

 clr_callback.py		 'Pet Adoption (CB) - PC.ipynb'
 Dataset			 'Pet Adoption (EDA).ipynb'
 learningratefinder.py		 'Pet Adoption (LGB) - BC.ipynb'
'NPZ Files'			 'Pet Adoption (LGB) - PC.ipynb'
'Pet Adoption (ANN) - BC.ipynb'   Predictions
'Pet Adoption (ANN) - PC.ipynb'   __pycache__
'Pet Adoption (CB) - BC.ipynb'

## Download Packages

In [ ]:
! pip install optuna

Collecting optuna
  Downloading https://files.pythonhosted.org/packages/06/b0/9a6313c78bca92abfacc08a2ad8b27bfe845256f615786ee2b6452ae1978/optuna-2.0.0.tar.gz (226kB)
     |████████████████████████████████| 235kB 2.7MB/s
Collecting alembic
  Downloading https://files.pythonhosted.org/packages/60/1e/cabc75a189de0fbb2841d0975243e59bde8b7822bacbb95008ac6fe9ad47/alembic-1.4.2.tar.gz (1.1MB)
     |████████████████████████████████| 1.1MB 8.6MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cliff
  Downloading https://files.pythonhosted.org/packages/71/06/03b1f92d46546a18eabf33ff7f37ef422c18c93d5a926bf590fee32ebe75/cliff-3.4.0-py3-none-any.whl (76kB)
     |████████████████████████████████| 81kB 7.4MB/s
Collecting cmaes>=0.5.1
  Downloading https://files.pythonhosted.org/packages/63/88/d5e9b78151dce671d7e78ee4cc8905d83208254caa2a386b163ae0ab0027/cmaes-0.6.0-py3-none-any.whl
Collecting colorlog
  Downloading https://files.pythonhosted.org/packages/2a/81/12d77537c82c5d46aa2721dfee25a0e873ef5920ebd0827152f411effb57/colorlog-4.2.1-py2.py3-none-any.whl
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from optuna) (0.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from optuna) (1.18.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from optuna) (20.4)
Requirement already satisfied: scipy!=1.4.0 in /usr/local/lib/python3.6/dist-packages (from optuna) (1.4.1)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from optuna) (1.3.18)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from optuna) (4.41.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from alembic->optuna) (2.8.1)
Collecting Mako
  Downloading https://files.pythonhosted.org/packages/a6/37/0e706200d22172eb8fa17d68a7ae22dec7631a0a92266634fb518a88a5b2/Mako-1.1.3-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 7.3MB/s
Collecting python-editor>=0.3
  Downloading https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl
Collecting cmd2!=0.8.3,>=0.8.0
  Downloading https://files.pythonhosted.org/packages/fd/f3/c1ebff567b8dba74eaa26f52bceda3242200ef092fafb56fcc4e105d5953/cmd2-1.3.4-py3-none-any.whl (130kB)
     |████████████████████████████████| 133kB 18.9MB/s
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (1.15.0)
Collecting stevedore>=2.0.1
  Downloading https://files.pythonhosted.org/packages/d6/f4/041afc90e684f2b7d00a7f49abcbaf0b8c03e916bbc398ce49dce2a3c408/stevedore-3.2.0-py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 5.0MB/s
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (2.4.7)
Requirement already satisfied: PrettyTable<0.8,>=0.7.2 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (0.7.2)
Collecting pbr!=2.1.0,>=2.0.0
  Downloading https://files.pythonhosted.org/packages/96/ba/aa953a11ec014b23df057ecdbc922fdb40ca8463466b1193f3367d2711a6/pbr-5.4.5-py2.py3-none-any.whl (110kB)
     |████████████████████████████████| 112kB 14.8MB/s
Requirement already satisfied: PyYAML>=3.12 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (3.13)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.6/dist-packages (from Mako->alembic->optuna) (1.1.1)
Collecting pyperclip>=1.6
  Downloading https://files.pythonhosted.org/packages/f6/5b/55866e1cde0f86f5eec59dab5de8a66628cb0d53da74b8dbc15ad8dabda3/pyperclip-1.8.0.tar.gz
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (19.3.0)
Requirement already satisfied: importlib-metadata>=1.6.0; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (1.7.0)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (0.2.5)
Collecting colorama>=0.3.7
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=34.4 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (49.2.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata>=1.6.0; python_version < "3.8"->cmd2!=0.8.3,>=0.8.0->cliff->optuna) (3.1.0)
Building wheels for collected packages: alembic
  Building wheel for alembic (PEP 517) ... done
  Created wheel for alembic: filename=alembic-1.4.2-cp36-none-any.whl size=159543 sha256=c031fecf216cf0c701aa3f784d29e4bb978460adf3054f520aa0668f70c869a7
  Stored in directory: /root/.cache/pip/wheels/1f/04/83/76023f7a4c14688c0b5c2682a96392cfdd3ee4449eaaa287ef
Successfully built alembic
Building wheels for collected packages: optuna, pyperclip
  Building wheel for optuna (setup.py) ... done
  Created wheel for optuna: filename=optuna-2.0.0-cp36-none-any.whl size=312964 sha256=aed6ab18443c02118ca36c9f179043c7d5129743cb0ab860288bf0dd270f369b
  Stored in directory: /root/.cache/pip/wheels/b5/c9/03/c45484454bf657ffed0ed6af153bd3d213928df115eb2a56eb
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.0-cp36-none-any.whl size=8693 sha256=4d4e13ab068e9000c5fa89a3aa907b7a121403298fa576ceecdf68af32430a20
  Stored in directory: /root/.cache/pip/wheels/b2/ac/0a/b784f0afe26eaf52e88a7e15c7369090deea0354fa1c6fc689
Successfully built optuna pyperclip
Installing collected packages: Mako, python-editor, alembic, pyperclip, colorama, cmd2, pbr, stevedore, cliff, cmaes, colorlog, optuna
Successfully installed Mako-1.1.3 alembic-1.4.2 cliff-3.4.0 cmaes-0.6.0 cmd2-1.3.4 colorama-0.4.3 colorlog-4.2.1 optuna-2.0.0 pbr-5.4.5 pyperclip-1.8.0 python-editor-1.0.4 stevedore-3.2.0

## Import Packages

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import StratifiedKFold, StratifiedShuffleSplit
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE, ADASYN
from sklearn.decomposition import PCA
import featuretools as ft
from xgboost import XGBClassifier
import optuna

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)

## Set file paths for train and predict datasets

In [ ]:
train_dataset = "/content/drive/My Drive/Colab Notebooks/Adopt a Buddy/Dataset/train.csv"
predict_dataset = "/content/drive/My Drive/Colab Notebooks/Adopt a Buddy/Dataset/test.csv"

## Data Preprocessing

### Read train and predict datasets

In [ ]:
train_df = pd.read_csv(train_dataset)
predict_df = pd.read_csv(predict_dataset)
print("train_df: {}".format(train_df.shape))
print("predict_df: {}".format(predict_df.shape))

train_df: (18834, 11)
predict_df: (8072, 9)

### Extract target variables into NumPy arrays

In [ ]:
train_df['pet_category'] = train_df['pet_category'].apply(lambda x: 3 if x==4 else x)
train_y_pc = np.array([train_df['pet_category'].values]).T
train_df.drop(['breed_category','pet_category'], inplace=True, axis=1)
print("train_y_pc: {}".format(train_y_pc.shape))

train_y_pc: (18834, 1)

In [ ]:
temp_df = pd.DataFrame(train_y_pc, columns=['Class'])
temp_df.groupby(['Class']).size().reset_index().rename(columns={0:'count'})

   Class  count
0      0     88
1      1   7184
2      2  10621
3      3    941

### Combine train and predict dataframes

In [ ]:
combined_df = train_df.append(predict_df, sort=False, ignore_index=True)
combined_df.head()

       pet_id           issue_date         listing_date  ...  height(cm)  X1  X2
0  ANSL_69903  2016-07-10 00:00:00  2016-09-21 16:25:00  ...        7.78  13   9
1  ANSL_66892  2013-11-21 00:00:00  2018-12-27 17:47:00  ...       14.19  13   9
2  ANSL_69750  2014-09-28 00:00:00  2016-10-19 08:24:00  ...       40.90  15   4
3  ANSL_71623  2016-12-31 00:00:00  2019-01-25 18:30:00  ...       17.82   0   1
4  ANSL_57969  2017-09-28 00:00:00  2017-11-19 09:38:00  ...       11.06  18   4

[5 rows x 9 columns]

### Feature Engineering

#### Issue Date and Listing Date

In [ ]:
combined_df['iss_dt_year'] = combined_df['issue_date'].map(lambda x: pd.to_datetime(x).year)
combined_df['iss_dt_quarter'] = combined_df['issue_date'].map(lambda x: pd.to_datetime(x).quarter)
combined_df['iss_dt_month'] = combined_df['issue_date'].map(lambda x: pd.to_datetime(x).month)
combined_df['iss_dt_week'] = combined_df['issue_date'].map(lambda x: pd.to_datetime(x).week)
combined_df['iss_dt_day_year'] = combined_df['issue_date'].map(lambda x: pd.to_datetime(x).dayofyear)
combined_df['iss_dt_day_month'] = combined_df['issue_date'].map(lambda x: pd.to_datetime(x).day)
combined_df['iss_dt_day_week'] = combined_df['issue_date'].map(lambda x: pd.to_datetime(x).dayofweek)
combined_df['iss_dt_day_weekend'] = np.where(combined_df['iss_dt_day_week'].isin([5,6]),1,0)

In [ ]:
combined_df['lst_dt_year'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).year)
combined_df['lst_dt_quarter'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).quarter)
combined_df['lst_dt_month'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).month)
combined_df['lst_dt_week'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).week)
combined_df['lst_dt_day_year'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).dayofyear)
combined_df['lst_dt_day_month'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).day)
combined_df['lst_dt_day_week'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).dayofweek)
combined_df['lst_dt_day_weekend'] = np.where(combined_df['lst_dt_day_week'].isin([5,6]),1,0)
combined_df['lst_dt_hour'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).hour)
combined_df['lst_dt_minute'] = combined_df['listing_date'].map(lambda x: pd.to_datetime(x).minute)
combined_df['lst_dt_minutes_elapsed'] = combined_df['listing_date'].map(lambda x: (pd.to_datetime(x) - pd.to_datetime(pd.to_datetime(x).date())).seconds / 60.0)

In [ ]:
combined_df['dt_diff'] = (pd.to_datetime(combined_df['listing_date']) - pd.to_datetime(combined_df['issue_date']))
combined_df['dt_diff_days'] = combined_df['dt_diff']/np.timedelta64(1,'D')
combined_df['dt_diff_weeks'] = combined_df['dt_diff']/np.timedelta64(1,'W')
combined_df['dt_diff_mnths'] = combined_df['dt_diff']/np.timedelta64(1,'M')
combined_df['dt_diff_yrs'] = combined_df['dt_diff']/np.timedelta64(1,'Y')
combined_df['dt_diff_sec'] = combined_df['dt_diff']/np.timedelta64(1,'s')
combined_df['dt_diff_min'] = combined_df['dt_diff']/np.timedelta64(1,'m')
combined_df['dt_diff_hrs'] = combined_df['dt_diff']/np.timedelta64(1,'h')

In [ ]:
combined_df['curr_iss_dt_diff'] = (pd.datetime.now() - pd.to_datetime(combined_df['issue_date']))
combined_df['curr_iss_dt_diff_mnths'] = combined_df['curr_iss_dt_diff']/np.timedelta64(1,'M')
combined_df['curr_iss_dt_diff_yrs'] = combined_df['curr_iss_dt_diff']/np.timedelta64(1,'Y')

combined_df['curr_lst_dt_diff'] = (pd.datetime.now() - pd.to_datetime(combined_df['listing_date']))
combined_df['curr_lst_dt_diff_mnths'] = combined_df['curr_lst_dt_diff']/np.timedelta64(1,'M')
combined_df['curr_lst_dt_diff_yrs'] = combined_df['curr_lst_dt_diff']/np.timedelta64(1,'Y')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning:

The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime instead.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning:

The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime instead.

In [ ]:
combined_df.head()

       pet_id  ... curr_lst_dt_diff_yrs
0  ANSL_69903  ...             3.917395
1  ANSL_66892  ...             1.652990
2  ANSL_69750  ...             3.841648
3  ANSL_71623  ...             1.573509
4  ANSL_57969  ...             2.757296

[5 rows x 42 columns]

#### Condition

In [ ]:
combined_df['condition'] = combined_df['condition'].fillna(value=3)

In [ ]:
dummy_val = pd.get_dummies(combined_df['condition'], prefix='condition')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

In [ ]:
combined_df['condition_odd_even'] = combined_df['condition'].apply(lambda x: 'EVEN' if x%2==0 else 'ODD')
dummy_val = pd.get_dummies(combined_df['condition_odd_even'], prefix='condition_odd_even')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

combined_df['condition*X1'] = np.cbrt(combined_df['condition'] * combined_df['X1'])
combined_df['condition*X2'] = combined_df['condition'] * combined_df['X2']

In [ ]:
combined_df['condition%X1'] = combined_df.apply(lambda row: 0 if row['condition']==0 else row['X1']%row['condition'], axis=1)
combined_df['condition%X2'] = combined_df.apply(lambda row: 0 if row['condition']==0 else row['X2']%row['condition'], axis=1)

#### Pet Id

In [ ]:
combined_df['pet_id_num'] = combined_df['pet_id'].apply(lambda x: x.split('_')[1]).astype(int)
combined_df.head()

       pet_id           issue_date  ... condition%X2  pet_id_num
0  ANSL_69903  2016-07-10 00:00:00  ...          1.0       69903
1  ANSL_66892  2013-11-21 00:00:00  ...          0.0       66892
2  ANSL_69750  2014-09-28 00:00:00  ...          1.0       69750
3  ANSL_71623  2016-12-31 00:00:00  ...          0.0       71623
4  ANSL_57969  2017-09-28 00:00:00  ...          0.0       57969

[5 rows x 54 columns]

In [ ]:
combined_df['pet_id_odd'] = combined_df['pet_id_num'].apply(lambda x: 0 if x%2==0 else 1)
combined_df['pet_id_even'] = combined_df['pet_id_num'].apply(lambda x: 1 if x%2==0 else 0)
combined_df['petid%X1'] = combined_df.apply(lambda row: 0 if row['X1']==0 else row['pet_id_num']%row['X1'], axis=1)
combined_df['petid%X2'] = combined_df.apply(lambda row: 0 if row['X2']==0 else row['pet_id_num']%row['X2'], axis=1)
combined_df['petid%condition'] = combined_df.apply(lambda row: 0 if row['condition']==0 else row['pet_id_num']%row['condition'], axis=1)

In [ ]:
combined_df['pet_id_0'] = combined_df['pet_id_num'].apply(lambda x: int(str(x)[0]))
combined_df['pet_id_1'] = combined_df['pet_id_num'].apply(lambda x: int(str(x)[1]))
combined_df['pet_id_2'] = combined_df['pet_id_num'].apply(lambda x: int(str(x)[2]))
combined_df['pet_id_3'] = combined_df['pet_id_num'].apply(lambda x: int(str(x)[3]))
combined_df['pet_id_4'] = combined_df['pet_id_num'].apply(lambda x: int(str(x)[4]))

In [ ]:
combined_df.head()

       pet_id           issue_date  ... pet_id_3  pet_id_4
0  ANSL_69903  2016-07-10 00:00:00  ...        0         3
1  ANSL_66892  2013-11-21 00:00:00  ...        9         2
2  ANSL_69750  2014-09-28 00:00:00  ...        5         0
3  ANSL_71623  2016-12-31 00:00:00  ...        2         3
4  ANSL_57969  2017-09-28 00:00:00  ...        6         9

[5 rows x 64 columns]

#### Length and Height

In [ ]:
combined_df['height(m)'] = combined_df['height(cm)']/100

In [ ]:
combined_df['length_scale_10'] = np.array(np.round((combined_df['length(m)'] * 10)), dtype='int')
combined_df['length_scale_100'] = np.array(np.round((combined_df['length(m)'] * 100)), dtype='int')

In [ ]:
combined_df['height_scale_10'] = np.array(np.round((combined_df['height(m)'] * 10)), dtype='int')
combined_df['height_scale_100'] = np.array(np.round((combined_df['height(m)'] * 100)), dtype='int')
combined_df['height_scale_1000'] = np.array(np.round((combined_df['height(m)'] * 1000)), dtype='int')

In [ ]:
combined_df['diag(cm)'] = np.sqrt(combined_df['length(m)']**2 + combined_df['height(m)']**2)*100
combined_df['cbrt(m)'] = np.cbrt(combined_df['length(m)']**2 + combined_df['height(m)']**2)
combined_df['area(m)'] = np.sqrt(combined_df['length(m)'] * combined_df['height(m)'])

In [ ]:
combined_df['l=h'] = combined_df.apply(lambda row: 1 if np.round(row['length(m)'],1)==np.round(row['height(m)'],1) else 0, axis=1)
combined_df['l>h'] = combined_df.apply(lambda row: 1 if np.round(row['length(m)'],1)>np.round(row['height(m)'],1) else 0, axis=1)
combined_df['l<h'] = combined_df.apply(lambda row: 1 if np.round(row['length(m)'],1)<np.round(row['height(m)'],1) else 0, axis=1)

In [ ]:
combined_df['pet_size'] = combined_df['diag(cm)'].apply(lambda x: 'SMALL' if x<=40 else 'MEDIUM' if x>40 and x<=80 else 'BIG')
dummy_val = pd.get_dummies(combined_df['pet_size'], prefix='pet_size')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

#### Color Type

In [ ]:
combined_df['subcolor_type1'] = combined_df['color_type'].apply(lambda x: x.split()[0])
dummy_val = pd.get_dummies(combined_df['subcolor_type1'], prefix='subcolor_type1')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

In [ ]:
combined_df['subcolor_type2'] = combined_df['color_type'].apply(lambda x: 'NONE' if len(x.split())==1 else x.split()[1])
dummy_val = pd.get_dummies(combined_df['subcolor_type2'], prefix='subcolor_type2')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

In [ ]:
combined_df["color_type_num_words"] = combined_df["color_type"].apply(lambda x: len(str(x).split()))
combined_df["color_type_num_chars"] = combined_df["color_type"].apply(lambda x: len(str(x)))

In [ ]:
tfidf = TfidfVectorizer(analyzer='char')
features = tfidf.fit_transform(combined_df.color_type).toarray()
features_df = pd.DataFrame(features, columns=tfidf.get_feature_names())
print(features_df.shape)
combined_df = pd.merge(combined_df, features_df, left_index=True, right_index=True)

(26906, 24)

In [ ]:
countvec = CountVectorizer(analyzer='char')
features = countvec.fit_transform(combined_df.color_type).toarray()
features_df = pd.DataFrame(features, columns=countvec.get_feature_names())
print(features_df.shape)
combined_df = pd.merge(combined_df, features_df, left_index=True, right_index=True)

(26906, 24)

#### X1 and X2

In [ ]:
dummy_val = pd.get_dummies(combined_df['X1'], prefix='X1')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

dummy_val = pd.get_dummies(combined_df['X2'], prefix='X2')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

In [ ]:
combined_df['X1_odd_even'] = combined_df['X1'].apply(lambda x: 'EVEN' if x%2==0 else 'ODD')
dummy_val = pd.get_dummies(combined_df['X1_odd_even'], prefix='X1_odd_even')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

combined_df['X2_odd_even'] = combined_df['X2'].apply(lambda x: 'EVEN' if x%2==0 else 'ODD')
dummy_val = pd.get_dummies(combined_df['X2_odd_even'], prefix='X2_odd_even')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

In [ ]:
combined_df['Xavg'] = (combined_df['X1']+combined_df['X2'])/2
combined_df['Xdiff'] = np.abs(combined_df['X1']-combined_df['X2'])
combined_df['Xmul'] = combined_df['X1']*combined_df['X2']
combined_df['Xdiv'] = combined_df.apply(lambda row: 0 if row['X1']==0 or row['X2']==0 else row['X2']/row['X1'], axis=1)
combined_df['Xdiv'] = np.cbrt(combined_df['Xdiv'])
combined_df['Xmod'] = combined_df.apply(lambda row: 0 if row['X1']==0 or row['X2']==0 else row['X1']/row['X2'], axis=1)
combined_df['Xdiag'] = np.sqrt(combined_df['X1']**2 + combined_df['X2']**2)
combined_df['Xcbrt'] = np.cbrt(combined_df['X1']**2 + combined_df['X2']**2)

In [ ]:
combined_df['X1_cat'] = combined_df['X1'].apply(lambda x: '<=6' if x<=6 else '6to13' if x>6 and x<=13 else '>13')
dummy_val = pd.get_dummies(combined_df['X1_cat'], prefix='X1_cat')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

combined_df['X2_cat'] = combined_df['X2'].apply(lambda x: '<=3' if x<=3 else '4to7' if x>3 and x<=7 else '>7')
dummy_val = pd.get_dummies(combined_df['X2_cat'], prefix='X2_cat')
combined_df = pd.concat([combined_df, dummy_val], axis=1)

In [ ]:
combined_df['X1=X2'] = combined_df.apply(lambda row: 1 if row['X1']==row['X2'] else 0, axis=1)
combined_df['X1>X2'] = combined_df.apply(lambda row: 1 if row['X1']>row['X2'] else 0, axis=1)
combined_df['X1<X2'] = combined_df.apply(lambda row: 1 if row['X1']<row['X2'] else 0, axis=1)

In [ ]:
#combined_df['length/X1'] = combined_df.apply(lambda row: 0 if row['length(m)']==0 or row['X1']==0 else row['length(m)']/row['X1'], axis=1)
combined_df['length/X2'] = combined_df.apply(lambda row: 0 if row['length(m)']==0 or row['X2']==0 else row['length(m)']/row['X2'], axis=1)
combined_df['length/Xavg'] = combined_df.apply(lambda row: 0 if row['length(m)']==0 or row['Xavg']==0 else np.log1p(row['length(m)']/row['Xavg']), axis=1)
combined_df['length/Xdiag'] = combined_df.apply(lambda row: 0 if row['length(m)']==0 or row['Xdiag']==0 else np.log1p(row['length(m)']/row['Xdiag']), axis=1)

In [ ]:
#combined_df['height/X1'] = combined_df.apply(lambda row: 0 if row['height(m)']==0 or row['X1']==0 else row['height(m)']/row['X1'], axis=1)
combined_df['height/X2'] = combined_df.apply(lambda row: 0 if row['height(m)']==0 or row['X2']==0 else row['height(m)']/row['X2'], axis=1)
combined_df['height/Xavg'] = combined_df.apply(lambda row: 0 if row['height(m)']==0 or row['Xavg']==0 else np.log1p(row['height(m)']/row['Xavg']), axis=1)
combined_df['height/Xdiag'] = combined_df.apply(lambda row: 0 if row['height(m)']==0 or row['Xdiag']==0 else np.log1p(row['height(m)']/row['Xdiag']), axis=1)

In [ ]:
#combined_df['diag/X1'] = combined_df.apply(lambda row: 0 if row['diag(cm)']==0 or row['X1']==0 else row['diag(cm)']/row['X1'], axis=1)
combined_df['diag/X2'] = combined_df.apply(lambda row: 0 if row['diag(cm)']==0 or row['X2']==0 else row['diag(cm)']/row['X2'], axis=1)
combined_df['diag/Xavg'] = combined_df.apply(lambda row: 0 if row['diag(cm)']==0 or row['Xavg']==0 else np.log1p(row['diag(cm)']/row['Xavg']), axis=1)
combined_df['diag/Xdiag'] = combined_df.apply(lambda row: 0 if row['diag(cm)']==0 or row['Xdiag']==0 else np.log1p(row['diag(cm)']/row['Xdiag']), axis=1)

In [ ]:
#combined_df['area/X1'] = combined_df.apply(lambda row: 0 if row['area(m)']==0 or row['X1']==0 else row['area(m)']/row['X1'], axis=1)
combined_df['area/X2'] = combined_df.apply(lambda row: 0 if row['area(m)']==0 or row['X2']==0 else row['area(m)']/row['X2'], axis=1)
combined_df['area/Xavg'] = combined_df.apply(lambda row: 0 if row['area(m)']==0 or row['Xavg']==0 else np.log1p(row['area(m)']/row['Xavg']), axis=1)
combined_df['area/Xdiag'] = combined_df.apply(lambda row: 0 if row['area(m)']==0 or row['Xdiag']==0 else np.log1p(row['area(m)']/row['Xdiag']), axis=1)

#### Drop redundant fields

In [ ]:
combined_df.drop(['condition_odd_even','color_type', 'height(cm)', 'issue_date', 'listing_date', 'dt_diff', 'X1_cat', 'X2_cat', 'X1_odd_even', 
                  'X2_odd_even', 'pet_size', 'subcolor_type1', 'subcolor_type2', 'curr_iss_dt_diff', 'curr_lst_dt_diff'], axis=1, inplace=True)
combined_df.head()

       pet_id  condition  length(m)  ...   area/X2  area/Xavg  area/Xdiag
0  ANSL_69903        2.0       0.80  ...  0.027720   0.022427    0.015655
1  ANSL_66892        1.0       0.72  ...  0.035515   0.028644    0.020014
2  ANSL_69750        3.0       0.15  ...  0.061922   0.025738    0.015829
3  ANSL_71623        1.0       0.62  ...  0.332391   0.509695    0.286975
4  ANSL_57969        2.0       0.50  ...  0.058790   0.021153    0.012673

[5 rows x 222 columns]

#### Feature Tools

In [ ]:
feature_df = pd.DataFrame()
feature_df = combined_df[['pet_id','height(m)','length(m)','diag(cm)','area(m)','pet_id_num','petid%X1','petid%X2',
                          'length_scale_10','length_scale_100','height_scale_10','height_scale_100','height_scale_1000',
                          'pet_id_0','pet_id_1','pet_id_2','pet_id_3','pet_id_4',
                          'Xavg','Xdiff','Xmul','Xdiv','Xmod','Xdiag','Xcbrt','condition','X1','X2']]
feature_df.head()

       pet_id  height(m)  length(m)   diag(cm)  ...     Xcbrt  condition  X1  X2
0  ANSL_69903     0.0778       0.80  80.377412  ...  6.299605        2.0  13   9
1  ANSL_66892     0.1419       0.72  73.384986  ...  6.299605        1.0  13   9
2  ANSL_69750     0.4090       0.15  43.563861  ...  6.223084        3.0  15   4
3  ANSL_71623     0.1782       0.62  64.510095  ...  1.000000        1.0   0   1
4  ANSL_57969     0.1106       0.50  51.208628  ...  6.979532        2.0  18   4

[5 rows x 28 columns]

In [ ]:
es = ft.EntitySet(id='Buddy')
es.entity_from_dataframe(entity_id='Breed_Category', dataframe=feature_df, index='pet_id')
es = es.normalize_entity(base_entity_id='Breed_Category', new_entity_id='condition', index='condition')
es = es.normalize_entity(base_entity_id='Breed_Category', new_entity_id='X1', index='X1')
es = es.normalize_entity(base_entity_id='Breed_Category', new_entity_id='X2', index='X2')
feature_matrix, feature_names = ft.dfs(entityset=es, target_entity='Breed_Category', max_depth=2, verbose=3, n_jobs=1)
print(feature_matrix.shape)
feature_matrix.head()

Built 474 features
Elapsed: 00:18 | Remaining: 00:00 | Progress: 100%|██████████| Calculated: 11/11 chunks
(26906, 474)

            height(m)  ...  X2.MODE(Breed_Category.X1)
pet_id                 ...
ANSL_49970     0.4595  ...                           0
ANSL_49971     0.0938  ...                          13
ANSL_49972     0.2681  ...                           0
ANSL_49973     0.3674  ...                          13
ANSL_49974     0.2317  ...                          13

[5 rows x 474 columns]

In [ ]:
feature_matrix.drop(['height(m)','length(m)','diag(cm)','area(m)','pet_id_num','petid%X1','petid%X2',
                     'length_scale_10','length_scale_100','height_scale_10','height_scale_100','height_scale_1000',
                     'pet_id_0','pet_id_1','pet_id_2','pet_id_3','pet_id_4',
                     'Xavg','Xdiff','Xmul','Xdiv','Xmod','Xdiag','Xcbrt','condition','X1','X2'], axis=1, inplace=True)
feature_df = feature_matrix.copy()

In [ ]:
combined_df.set_index('pet_id', inplace = True)
combined_df.drop(['condition','pet_id_num'], axis=1, inplace=True)
print(combined_df.shape)
combined_df.head()

(26906, 219)

            length(m)  X1  X2  ...   area/X2  area/Xavg  area/Xdiag
pet_id                         ...
ANSL_69903       0.80  13   9  ...  0.027720   0.022427    0.015655
ANSL_66892       0.72  13   9  ...  0.035515   0.028644    0.020014
ANSL_69750       0.15  15   4  ...  0.061922   0.025738    0.015829
ANSL_71623       0.62   0   1  ...  0.332391   0.509695    0.286975
ANSL_57969       0.50  18   4  ...  0.058790   0.021153    0.012673

[5 rows x 219 columns]

In [ ]:
temp_df = pd.merge(combined_df, feature_df, how='inner', on='pet_id', sort=False, suffixes=('_x', '_y'))
print(temp_df.shape)
temp_df.head()

(26906, 666)

            length(m)  ...  X2.MODE(Breed_Category.X1)
pet_id                 ...
ANSL_69903       0.80  ...                          13
ANSL_66892       0.72  ...                          13
ANSL_69750       0.15  ...                          15
ANSL_71623       0.62  ...                           0
ANSL_57969       0.50  ...                          15

[5 rows x 666 columns]

In [ ]:
temp_df.fillna(0, inplace=True)
temp_df[temp_df.isin([np.nan, np.inf, -np.inf]).any(1)].head()

Empty DataFrame
Columns: [length(m), X1, X2, iss_dt_year, iss_dt_quarter, iss_dt_month, iss_dt_week, iss_dt_day_year, iss_dt_day_month, iss_dt_day_week, iss_dt_day_weekend, lst_dt_year, lst_dt_quarter, lst_dt_month, lst_dt_week, lst_dt_day_year, lst_dt_day_month, lst_dt_day_week, lst_dt_day_weekend, lst_dt_hour, lst_dt_minute, lst_dt_minutes_elapsed, dt_diff_days, dt_diff_weeks, dt_diff_mnths, dt_diff_yrs, dt_diff_sec, dt_diff_min, dt_diff_hrs, curr_iss_dt_diff_mnths, curr_iss_dt_diff_yrs, curr_lst_dt_diff_mnths, curr_lst_dt_diff_yrs, condition_0.0, condition_1.0, condition_2.0, condition_3.0, condition_odd_even_EVEN, condition_odd_even_ODD, condition*X1, condition*X2, condition%X1, condition%X2, pet_id_odd, pet_id_even, petid%X1, petid%X2, petid%condition, pet_id_0, pet_id_1, pet_id_2, pet_id_3, pet_id_4, height(m), length_scale_10, length_scale_100, height_scale_10, height_scale_100, height_scale_1000, diag(cm), cbrt(m), area(m), l=h, l>h, l<h, pet_size_BIG, pet_size_MEDIUM, pet_size_SMALL, subcolor_type1_Agouti, subcolor_type1_Apricot, subcolor_type1_Black, subcolor_type1_Blue, subcolor_type1_Brown, subcolor_type1_Buff, subcolor_type1_Calico, subcolor_type1_Chocolate, subcolor_type1_Cream, subcolor_type1_Fawn, subcolor_type1_Flame, subcolor_type1_Gold, subcolor_type1_Gray, subcolor_type1_Green, subcolor_type1_Lilac, subcolor_type1_Liver, subcolor_type1_Lynx, subcolor_type1_Orange, subcolor_type1_Pink, subcolor_type1_Red, subcolor_type1_Sable, subcolor_type1_Seal, subcolor_type1_Silver, subcolor_type1_Tan, subcolor_type1_Torbie, subcolor_type1_Tortie, subcolor_type1_Tricolor, subcolor_type1_White, subcolor_type1_Yellow, subcolor_type2_Brindle, subcolor_type2_Cream, subcolor_type2_Lynx, ...]
Index: []

[0 rows x 666 columns]

In [ ]:
combined_df = temp_df.copy()

### Create train and predict Numpy arrays

In [ ]:
# Segregate combined_df into train/predict datasets
train_x = combined_df[:18834].values
predict_x = combined_df[18834:].values

print("train_x: {}".format(train_x.shape))
print("predict_x: {}".format(predict_x.shape))

train_x: (18834, 666)
predict_x: (8072, 666)

In [ ]:
# Scale the train_x/predict_x arrays
#scaler = MinMaxScaler().fit(train_x)
scaler = StandardScaler().fit(train_x)
train_x_pc = scaler.transform(train_x)
Xpredict = scaler.transform(predict_x)

### Feature Selection

In [ ]:
pca = PCA(.999)
pca.fit(train_x_pc)

PCA(copy=True, iterated_power='auto', n_components=0.999, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
train_x_pc = pca.transform(train_x_pc)
Xpredict = pca.transform(Xpredict)

print("train_x_pc: {} \nXpredict: {}".format(train_x_pc.shape, Xpredict.shape))

train_x_pc: (18834, 100)
Xpredict: (8072, 100)

### Split training data into train/ validation/ test datasets

In [ ]:
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=10)
for train_index, test_index in sss.split(train_x_pc, train_y_pc):
    Xtrain_pc, Xvalidation_pc = train_x_pc[train_index], train_x_pc[test_index]
    Ytrain_pc, Yvalidation_pc = train_y_pc[train_index], train_y_pc[test_index]

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.4, random_state=20)
for train_index, test_index in sss.split(Xvalidation_pc, Yvalidation_pc):
    Xvalidation_pc, Xtest_pc = Xvalidation_pc[train_index], Xvalidation_pc[test_index]
    Yvalidation_pc, Ytest_pc = Yvalidation_pc[train_index], Yvalidation_pc[test_index]


print("------------------------- Training Dataset -------------------------")
print("Xtrain_pc shape: {}".format(Xtrain_pc.shape))
print("Ytrain_pc shape: {}".format(Ytrain_pc.shape))

print("\n------------------------- Validation Dataset -------------------------")
print("Xvalidation_pc shape: {}".format(Xvalidation_pc.shape))
print("Yvalidation_pc shape: {}".format(Yvalidation_pc.shape))

print("\n------------------------- Test Dataset -------------------------")
print("Xtest_pc shape: {}".format(Xtest_pc.shape))
print("Ytest_pc shape: {}".format(Ytest_pc.shape))

print("\n------------------------- Prediction Dataset -------------------------")
print("Xpredict shape: {}".format(Xpredict.shape))

------------------------- Training Dataset -------------------------
Xtrain_pc shape: (15067, 100)
Ytrain_pc shape: (15067, 1)

------------------------- Validation Dataset -------------------------
Xvalidation_pc shape: (2260, 100)
Yvalidation_pc shape: (2260, 1)

------------------------- Test Dataset -------------------------
Xtest_pc shape: (1507, 100)
Ytest_pc shape: (1507, 1)

------------------------- Prediction Dataset -------------------------
Xpredict shape: (8072, 100)

### Handling class imbalance

In [ ]:
#sm = SMOTE()
sm = ADASYN()
sm_x, sm_y = sm.fit_sample(Xtrain_pc, Ytrain_pc.ravel())
Xtrain_pc = sm_x
Ytrain_pc = np.array([sm_y]).T
print("Class balancing done.")
print("Xtrain_pc shape: {}".format(Xtrain_pc.shape))
print("Ytrain_pc shape: {}".format(Ytrain_pc.shape))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning:

Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning:

Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning:

Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.

Class balancing done.
Xtrain_pc shape: (34542, 100)
Ytrain_pc shape: (34542, 1)

In [ ]:
temp_df = pd.DataFrame(Ytrain_pc, columns=['Class'])
temp_df.groupby(['Class']).size().reset_index().rename(columns={0:'count'})

   Class  count
0      0   8506
1      1   8944
2      2   8497
3      3   8595

In [ ]:
temp_df = pd.DataFrame(Yvalidation_pc, columns=['Class'])
temp_df.groupby(['Class']).size().reset_index().rename(columns={0:'count'})

   Class  count
0      0     11
1      1    862
2      2   1274
3      3    113

In [ ]:
temp_df = pd.DataFrame(Ytest_pc, columns=['Class'])
temp_df.groupby(['Class']).size().reset_index().rename(columns={0:'count'})

   Class  count
0      0      7
1      1    575
2      2    850
3      3     75

## Save the datasets in NPZ file (for reusability)

In [ ]:
np.savez_compressed('/content/drive/My Drive/Colab Notebooks/Adopt a Buddy/NPZ Files/Pet_Category_Dataset.npz',
                    Xtrain_pc=Xtrain_pc, Ytrain_pc=Ytrain_pc,
                    Xvalidation_pc=Xvalidation_pc, Yvalidation_pc=Yvalidation_pc,
                    Xtest_pc=Xtest_pc, Ytest_pc=Ytest_pc,
                    Xpredict=Xpredict)

## Load datasets from the NPZ file

In [ ]:
processed_dataset = np.load('/content/drive/My Drive/Colab Notebooks/Adopt a Buddy/NPZ Files/Pet_Category_Dataset.npz', allow_pickle=True)
Xtrain_pc, Ytrain_pc = processed_dataset['Xtrain_pc'], processed_dataset['Ytrain_pc']
Xvalidation_pc, Yvalidation_pc = processed_dataset['Xvalidation_pc'], processed_dataset['Yvalidation_pc']
Xtest_pc, Ytest_pc = processed_dataset['Xtest_pc'], processed_dataset['Ytest_pc']
Xpredict = processed_dataset['Xpredict']

print("------------------------- Training Dataset -------------------------")
print("Xtrain_pc shape: {}".format(Xtrain_pc.shape))
print("Ytrain_pc shape: {}".format(Ytrain_pc.shape))

print("\n------------------------- Validation Dataset -------------------------")
print("Xvalidation_pc shape: {}".format(Xvalidation_pc.shape))
print("Yvalidation_pc shape: {}".format(Yvalidation_pc.shape))

print("\n------------------------- Test Dataset -------------------------")
print("Xtest_pc shape: {}".format(Xtest_pc.shape))
print("Ytest_pc shape: {}".format(Ytest_pc.shape))

print("\n------------------------- Prediction Dataset -------------------------")
print("Xpredict shape: {}".format(Xpredict.shape))

------------------------- Training Dataset -------------------------
Xtrain_pc shape: (34542, 100)
Ytrain_pc shape: (34542, 1)

------------------------- Validation Dataset -------------------------
Xvalidation_pc shape: (2260, 100)
Yvalidation_pc shape: (2260, 1)

------------------------- Test Dataset -------------------------
Xtest_pc shape: (1507, 100)
Ytest_pc shape: (1507, 1)

------------------------- Prediction Dataset -------------------------
Xpredict shape: (8072, 100)

## Pet Category Prediction

### Hyperparameter search using Optuna

In [ ]:
def objective(trial):
    
    model = XGBClassifier(
        objective='multi:softmax',
        eval_metric='mlogloss',
        booster='gbtree',
        sample_type='uniform',
        tree_method='gpu_hist',
        grow_policy='lossguide',
        num_round=5000,
        num_class=4,
        max_depth=trial.suggest_int("max_depth", 6, 15), 
        max_leaves=trial.suggest_int("max_leaves", 35, 500),
        learning_rate=trial.suggest_loguniform("learning_rate", 1e-2, 1e-1),
        subsample=trial.suggest_uniform("subsample", 0.5, 1.0),
        colsample_bytree=trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
        min_child_weight=trial.suggest_int("min_child_weight", 1, 15),
        reg_lambda=trial.suggest_loguniform("reg_lambda", 1e-4, 1.0),
        verbosity=0
    )

    model.fit(Xtrain_pc, Ytrain_pc, eval_set=[(Xvalidation_pc, Yvalidation_pc)], early_stopping_rounds=200, verbose=False)
    y_pred = model.predict(Xtest_pc, ntree_limit=model.best_ntree_limit)
    y_pred = y_pred.astype(int)
    f1 = f1_score(Ytest_pc, y_pred, average='weighted')

    return f1

In [ ]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=500)

[I 2020-08-22 11:43:03,832] Trial 0 finished with value: 0.8759541525860076 and parameters: {'learning_rate': 0.029152492317020103, 'lambda_l2': 0.0007235030305763655, 'num_leaves': 588, 'max_depth': 10, 'feature_fraction': 0.6312077278218008, 'bagging_fraction': 0.6690764164365671, 'bagging_freq': 5, 'min_child_samples': 15, 'min_child_weight': 0.00575969932111108}. Best is trial 0 with value: 0.8759541525860076.
[I 2020-08-22 11:45:16,579] Trial 1 finished with value: 0.8687382093894845 and parameters: {'learning_rate': 0.033359217563393585, 'lambda_l2': 0.05306053706030071, 'num_leaves': 615, 'max_depth': 7, 'feature_fraction': 0.6711065526616959, 'bagging_fraction': 0.5346309846082608, 'bagging_freq': 11, 'min_child_samples': 7, 'min_child_weight': 0.004568900290824592}. Best is trial 0 with value: 0.8759541525860076.
[I 2020-08-22 11:47:30,177] Trial 2 finished with value: 0.8772003482146279 and parameters: {'learning_rate': 0.06956970762744775, 'lambda_l2': 0.7811146611783196, 'num_leaves': 2633, 'max_depth': 9, 'feature_fraction': 0.6483677482716714, 'bagging_fraction': 0.5562956851898881, 'bagging_freq': 14, 'min_child_samples': 2, 'min_child_weight': 0.0031567280177617935}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 11:52:18,590] Trial 3 finished with value: 0.8739658476640573 and parameters: {'learning_rate': 0.02887457457668893, 'lambda_l2': 0.0027604482727468815, 'num_leaves': 1290, 'max_depth': 12, 'feature_fraction': 0.6296718002100548, 'bagging_fraction': 0.638600010791869, 'bagging_freq': 13, 'min_child_samples': 4, 'min_child_weight': 0.06715811727354229}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 12:08:03,392] Trial 4 finished with value: 0.86387276703745 and parameters: {'learning_rate': 0.0016391759971841119, 'lambda_l2': 0.00016044888233795017, 'num_leaves': 1015, 'max_depth': 7, 'feature_fraction': 0.5067984090227998, 'bagging_fraction': 0.5686686991672871, 'bagging_freq': 12, 'min_child_samples': 7, 'min_child_weight': 0.0015822550443254967}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 12:29:57,881] Trial 5 finished with value: 0.8583826760036186 and parameters: {'learning_rate': 0.0010316499752934442, 'lambda_l2': 0.000841005215873747, 'num_leaves': 2775, 'max_depth': 8, 'feature_fraction': 0.5465610414051083, 'bagging_fraction': 0.5468581976364761, 'bagging_freq': 9, 'min_child_samples': 10, 'min_child_weight': 0.0010355154774323843}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 12:59:12,924] Trial 6 finished with value: 0.8733116110703464 and parameters: {'learning_rate': 0.0019132377104194658, 'lambda_l2': 0.40190296794200203, 'num_leaves': 1856, 'max_depth': 10, 'feature_fraction': 0.5443846947677871, 'bagging_fraction': 0.5229620521748233, 'bagging_freq': 12, 'min_child_samples': 9, 'min_child_weight': 0.030491613146973254}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 13:05:46,410] Trial 7 finished with value: 0.8740301902837323 and parameters: {'learning_rate': 0.013222095981263735, 'lambda_l2': 0.00418059240539709, 'num_leaves': 1366, 'max_depth': 9, 'feature_fraction': 0.6015119283921038, 'bagging_fraction': 0.6365904447333899, 'bagging_freq': 6, 'min_child_samples': 3, 'min_child_weight': 0.013393383469135496}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 13:18:38,428] Trial 8 finished with value: 0.8725651085820318 and parameters: {'learning_rate': 0.004567340642581771, 'lambda_l2': 0.00011440299910643802, 'num_leaves': 1437, 'max_depth': 7, 'feature_fraction': 0.6178764922877577, 'bagging_fraction': 0.6373612355508638, 'bagging_freq': 15, 'min_child_samples': 14, 'min_child_weight': 0.0186535940594543}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 13:31:12,110] Trial 9 finished with value: 0.8765576759825862 and parameters: {'learning_rate': 0.00612310396240213, 'lambda_l2': 0.7080645316413178, 'num_leaves': 944, 'max_depth': 11, 'feature_fraction': 0.6350016521173606, 'bagging_fraction': 0.563303249349616, 'bagging_freq': 8, 'min_child_samples': 12, 'min_child_weight': 0.035321290934845775}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 13:33:02,038] Trial 10 finished with value: 0.8727277875201959 and parameters: {'learning_rate': 0.09957433564172004, 'lambda_l2': 0.0756087318029759, 'num_leaves': 2759, 'max_depth': 9, 'feature_fraction': 0.695811094355907, 'bagging_fraction': 0.5966617064086526, 'bagging_freq': 15, 'min_child_samples': 1, 'min_child_weight': 0.0025309286496828626}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 13:46:34,149] Trial 11 finished with value: 0.8714053629295112 and parameters: {'learning_rate': 0.005764422202847852, 'lambda_l2': 0.9943841516020109, 'num_leaves': 2100, 'max_depth': 12, 'feature_fraction': 0.667251643099163, 'bagging_fraction': 0.5708260817402334, 'bagging_freq': 8, 'min_child_samples': 13, 'min_child_weight': 0.0894530075040311}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 13:47:50,414] Trial 12 finished with value: 0.8681460097886685 and parameters: {'learning_rate': 0.08823267907593253, 'lambda_l2': 0.23565814939980295, 'num_leaves': 115, 'max_depth': 11, 'feature_fraction': 0.6588771220694121, 'bagging_fraction': 0.500230373452708, 'bagging_freq': 7, 'min_child_samples': 11, 'min_child_weight': 0.04408790473966596}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 13:53:58,143] Trial 13 finished with value: 0.8732060577797495 and parameters: {'learning_rate': 0.01289765176291294, 'lambda_l2': 0.898513699163484, 'num_leaves': 2059, 'max_depth': 11, 'feature_fraction': 0.5716214241927322, 'bagging_fraction': 0.5930426312447294, 'bagging_freq': 10, 'min_child_samples': 12, 'min_child_weight': 0.0073010694708364205}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 14:16:12,471] Trial 14 finished with value: 0.876714717457916 and parameters: {'learning_rate': 0.004514707766855786, 'lambda_l2': 0.03136528370797834, 'num_leaves': 2434, 'max_depth': 11, 'feature_fraction': 0.6967455822964663, 'bagging_fraction': 0.5016571461563035, 'bagging_freq': 8, 'min_child_samples': 5, 'min_child_weight': 0.003077049837425168}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 14:41:08,965] Trial 15 finished with value: 0.875903604967859 and parameters: {'learning_rate': 0.0029430651092670524, 'lambda_l2': 0.023930045146157645, 'num_leaves': 2963, 'max_depth': 8, 'feature_fraction': 0.6994498481239348, 'bagging_fraction': 0.507432792876197, 'bagging_freq': 14, 'min_child_samples': 4, 'min_child_weight': 0.003293118205820143}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 14:44:01,918] Trial 16 finished with value: 0.8655819380325347 and parameters: {'learning_rate': 0.05985055821919835, 'lambda_l2': 0.13123231028685536, 'num_leaves': 2451, 'max_depth': 10, 'feature_fraction': 0.6874136326693597, 'bagging_fraction': 0.514383332900151, 'bagging_freq': 10, 'min_child_samples': 1, 'min_child_weight': 0.0017799120896851619}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 14:54:03,235] Trial 17 finished with value: 0.8746130191552621 and parameters: {'learning_rate': 0.008323335281980863, 'lambda_l2': 0.019529601289634414, 'num_leaves': 2464, 'max_depth': 9, 'feature_fraction': 0.6491331472079633, 'bagging_fraction': 0.5436924425981742, 'bagging_freq': 5, 'min_child_samples': 5, 'min_child_weight': 0.0010864098890349223}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 15:19:19,497] Trial 18 finished with value: 0.8739010794724243 and parameters: {'learning_rate': 0.0032989652649285644, 'lambda_l2': 0.00802660614383358, 'num_leaves': 2418, 'max_depth': 8, 'feature_fraction': 0.6805513339473135, 'bagging_fraction': 0.6115098662047381, 'bagging_freq': 7, 'min_child_samples': 2, 'min_child_weight': 0.0032124963130884306}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 15:23:55,300] Trial 19 finished with value: 0.87536745099735 and parameters: {'learning_rate': 0.020717383909442433, 'lambda_l2': 0.21675978607504132, 'num_leaves': 1779, 'max_depth': 11, 'feature_fraction': 0.5970923299085934, 'bagging_fraction': 0.5014349965708013, 'bagging_freq': 11, 'min_child_samples': 6, 'min_child_weight': 0.01038079954563991}. Best is trial 2 with value: 0.8772003482146279.
[I 2020-08-22 15:27:25,458] Trial 20 finished with value: 0.8702790276999256 and parameters: {'learning_rate': 0.05007108113483024, 'lambda_l2': 0.03264861541493042, 'num_leaves': 2211, 'max_depth': 12, 'feature_fraction': 0.6483079543884935, 'bagging_fraction': 0.5287116227827612, 'bagging_freq': 9, 'min_child_samples': 3, 'min_child_weight': 0.0019250424803934083}. Best is trial 2 with value: 0.8772003482146279.

In [ ]:
print("Number of finished trials: {}".format(len(study.trials)))

print("Best trial:")
trial = study.best_trial

print("Value: {}".format(trial.value))

print("Params: ")
for key, value in trial.params.items():
    print(" {}: {}".format(key, value))

Number of finished trials: 4
Best trial:
Value: 0.9726850199728011
Params:
 learning_rate: 0.024749049914449626
 lambda_l2: 0.00014343719683289563
 num_leaves: 1146
 max_depth: 10
 feature_fraction: 0.6506172469225204
 bagging_fraction: 0.591074232573548
 bagging_freq: 10
 min_child_samples: 6
 min_child_weight: 0.02999463823816238

### Build the model for pet-category prediction

In [ ]:
# Define K-fold cross validation test harness
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=25)
y_pred = 0

In [ ]:
Xtrain_tmp = np.concatenate((Xtrain_pc, Xvalidation_pc), axis=0)
Ytrain_tmp = np.concatenate((Ytrain_pc, Yvalidation_pc), axis=0)

In [ ]:
# Train the model using K-fold
counter = 0

for train, val in kfold.split(Xtrain_tmp, Ytrain_tmp):
    counter += 1

    train_x, train_y = Xtrain_tmp[train], Ytrain_tmp[train]
    val_x, val_y = Xtrain_tmp[val], Ytrain_tmp[val]
    
    model = XGBClassifier(
        objective='multi:softmax',
        eval_metric='mlogloss',
        booster='gbtree',
        sample_type='uniform',
        tree_method='gpu_hist',
        grow_policy='lossguide',
        num_round=5000,
        num_class=4,
        max_depth=trial.suggest_int("max_depth", 6, 15), 
        max_leaves=trial.suggest_int("max_leaves", 35, 500),
        learning_rate=trial.suggest_loguniform("learning_rate", 1e-2, 1e-1),
        subsample=trial.suggest_uniform("subsample", 0.5, 1.0),
        colsample_bytree=trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
        min_child_weight=trial.suggest_int("min_child_weight", 1, 15),
        reg_lambda=trial.suggest_loguniform("reg_lambda", 1e-4, 1.0),
        verbosity=0
    )
    
    pred = model.predict(Xtest_pc, ntree_limit=model.best_ntree_limit)
    y_pred += pred

y_pred /= float(counter)

Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.259918	valid_1's multi_logloss: 0.318236
[200]	training's multi_logloss: 0.108291	valid_1's multi_logloss: 0.181766
[300]	training's multi_logloss: 0.0535861	valid_1's multi_logloss: 0.136906
[400]	training's multi_logloss: 0.026079	valid_1's multi_logloss: 0.114255
[500]	training's multi_logloss: 0.0132138	valid_1's multi_logloss: 0.102527
[600]	training's multi_logloss: 0.0069534	valid_1's multi_logloss: 0.0956588
[700]	training's multi_logloss: 0.0038331	valid_1's multi_logloss: 0.092791
[800]	training's multi_logloss: 0.00215658	valid_1's multi_logloss: 0.091058
[900]	training's multi_logloss: 0.00134761	valid_1's multi_logloss: 0.0901057
[1000]	training's multi_logloss: 0.000886362	valid_1's multi_logloss: 0.0902559
[1100]	training's multi_logloss: 0.000639895	valid_1's multi_logloss: 0.0909802
Early stopping, best iteration is:
[904]	training's multi_logloss: 0.00131516	valid_1's multi_logloss: 0.0900223
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.261179	valid_1's multi_logloss: 0.315482
[200]	training's multi_logloss: 0.108851	valid_1's multi_logloss: 0.176266
[300]	training's multi_logloss: 0.0546968	valid_1's multi_logloss: 0.13168
[400]	training's multi_logloss: 0.0250716	valid_1's multi_logloss: 0.107727
[500]	training's multi_logloss: 0.0128036	valid_1's multi_logloss: 0.0959595
[600]	training's multi_logloss: 0.00693096	valid_1's multi_logloss: 0.0893037
[700]	training's multi_logloss: 0.00381224	valid_1's multi_logloss: 0.0852618
[800]	training's multi_logloss: 0.00216099	valid_1's multi_logloss: 0.0832958
[900]	training's multi_logloss: 0.00136777	valid_1's multi_logloss: 0.0821196
[1000]	training's multi_logloss: 0.000793575	valid_1's multi_logloss: 0.0821953
[1100]	training's multi_logloss: 0.000509341	valid_1's multi_logloss: 0.0825433
Early stopping, best iteration is:
[943]	training's multi_logloss: 0.00107577	valid_1's multi_logloss: 0.0819765
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.262833	valid_1's multi_logloss: 0.314981
[200]	training's multi_logloss: 0.111799	valid_1's multi_logloss: 0.174648
[300]	training's multi_logloss: 0.0548279	valid_1's multi_logloss: 0.127118
[400]	training's multi_logloss: 0.0270113	valid_1's multi_logloss: 0.103528
[500]	training's multi_logloss: 0.0137889	valid_1's multi_logloss: 0.0901909
[600]	training's multi_logloss: 0.0071053	valid_1's multi_logloss: 0.0835363
[700]	training's multi_logloss: 0.00391501	valid_1's multi_logloss: 0.0796277
[800]	training's multi_logloss: 0.00232561	valid_1's multi_logloss: 0.077531
[900]	training's multi_logloss: 0.00139932	valid_1's multi_logloss: 0.076339
[1000]	training's multi_logloss: 0.000855387	valid_1's multi_logloss: 0.0761319
[1100]	training's multi_logloss: 0.000583237	valid_1's multi_logloss: 0.076281
[1200]	training's multi_logloss: 0.000421075	valid_1's multi_logloss: 0.0764478
Early stopping, best iteration is:
[1060]	training's multi_logloss: 0.000673111	valid_1's multi_logloss: 0.0759783
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.259708	valid_1's multi_logloss: 0.312603
[200]	training's multi_logloss: 0.109746	valid_1's multi_logloss: 0.178194
[300]	training's multi_logloss: 0.0511284	valid_1's multi_logloss: 0.133047
[400]	training's multi_logloss: 0.0248684	valid_1's multi_logloss: 0.112887
[500]	training's multi_logloss: 0.0127723	valid_1's multi_logloss: 0.102782
[600]	training's multi_logloss: 0.00693613	valid_1's multi_logloss: 0.0977708
[700]	training's multi_logloss: 0.00393044	valid_1's multi_logloss: 0.0954868
[800]	training's multi_logloss: 0.00228031	valid_1's multi_logloss: 0.0939433
[900]	training's multi_logloss: 0.0014284	valid_1's multi_logloss: 0.0940062
[1000]	training's multi_logloss: 0.000962574	valid_1's multi_logloss: 0.0944484
Early stopping, best iteration is:
[858]	training's multi_logloss: 0.00172771	valid_1's multi_logloss: 0.0935692
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.259305	valid_1's multi_logloss: 0.316449
[200]	training's multi_logloss: 0.110596	valid_1's multi_logloss: 0.180636
[300]	training's multi_logloss: 0.052723	valid_1's multi_logloss: 0.133375
[400]	training's multi_logloss: 0.0267126	valid_1's multi_logloss: 0.111101
[500]	training's multi_logloss: 0.0141419	valid_1's multi_logloss: 0.099641
[600]	training's multi_logloss: 0.00790885	valid_1's multi_logloss: 0.0935045
[700]	training's multi_logloss: 0.00424092	valid_1's multi_logloss: 0.0898188
[800]	training's multi_logloss: 0.00228446	valid_1's multi_logloss: 0.0879334
[900]	training's multi_logloss: 0.00135713	valid_1's multi_logloss: 0.0873529
[1000]	training's multi_logloss: 0.000844376	valid_1's multi_logloss: 0.0872549
[1100]	training's multi_logloss: 0.000543368	valid_1's multi_logloss: 0.0881405
Early stopping, best iteration is:
[974]	training's multi_logloss: 0.000966946	valid_1's multi_logloss: 0.0869805

### Validate the model

In [ ]:
# Print log_loss, accuracy and F1-score
y_pred = y_pred.astype(int)
f1 = f1_score(Ytest_pc, y_pred, average='weighted')
print('Overall F1-Score:', f1)

Overall F1-Score: 0.9720884513848744

In [ ]:
print(classification_report(Ytest_pc, y_pred_binary))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       425
           1       0.93      0.98      0.95       449
           2       0.97      0.91      0.94       425
           3       0.99      1.00      1.00       428

    accuracy                           0.97      1727
   macro avg       0.97      0.97      0.97      1727
weighted avg       0.97      0.97      0.97      1727

### Train model on entire data

In [ ]:
# Define K-fold cross validation test harness
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=60)
y_pred_pc = 0

In [ ]:
Xtrain_tmp = np.concatenate((Xtrain_pc, Xvalidation_pc, Xtest_pc), axis=0)
Ytrain_tmp = np.concatenate((Ytrain_pc, Yvalidation_pc, Ytest_pc), axis=0)

In [ ]:
# Train the model using K-fold
counter = 0

for train, val in kfold.split(Xtrain_tmp, Ytrain_tmp):
    counter += 1

    train_x, train_y = Xtrain_tmp[train], Ytrain_tmp[train]
    val_x, val_y = Xtrain_tmp[val], Ytrain_tmp[val]
    
    model = XGBClassifier(
        objective='multi:softmax',
        eval_metric='mlogloss',
        booster='gbtree',
        sample_type='uniform',
        tree_method='gpu_hist',
        grow_policy='lossguide',
        num_round=5000,
        num_class=4,
        max_depth=trial.suggest_int("max_depth", 6, 15), 
        max_leaves=trial.suggest_int("max_leaves", 35, 500),
        learning_rate=trial.suggest_loguniform("learning_rate", 1e-2, 1e-1),
        subsample=trial.suggest_uniform("subsample", 0.5, 1.0),
        colsample_bytree=trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
        min_child_weight=trial.suggest_int("min_child_weight", 1, 15),
        reg_lambda=trial.suggest_loguniform("reg_lambda", 1e-4, 1.0),
        verbosity=0
    )
    
    pred = model.predict(Xpredict, ntree_limit=model.best_ntree_limit)
    y_pred_pc += pred

y_pred_pc /= float(counter)

Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.262354	valid_1's multi_logloss: 0.310353
[200]	training's multi_logloss: 0.112402	valid_1's multi_logloss: 0.173517
[300]	training's multi_logloss: 0.0546137	valid_1's multi_logloss: 0.126802
[400]	training's multi_logloss: 0.0263832	valid_1's multi_logloss: 0.103364
[500]	training's multi_logloss: 0.0137096	valid_1's multi_logloss: 0.0916874
[600]	training's multi_logloss: 0.00733556	valid_1's multi_logloss: 0.0850644
[700]	training's multi_logloss: 0.00393118	valid_1's multi_logloss: 0.0807534
[800]	training's multi_logloss: 0.00230194	valid_1's multi_logloss: 0.0789757
[900]	training's multi_logloss: 0.0013524	valid_1's multi_logloss: 0.078243
[1000]	training's multi_logloss: 0.000822681	valid_1's multi_logloss: 0.0779342
[1100]	training's multi_logloss: 0.000532344	valid_1's multi_logloss: 0.0782717
Early stopping, best iteration is:
[979]	training's multi_logloss: 0.00091072	valid_1's multi_logloss: 0.0777537
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.259781	valid_1's multi_logloss: 0.319681
[200]	training's multi_logloss: 0.10854	valid_1's multi_logloss: 0.182423
[300]	training's multi_logloss: 0.0523413	valid_1's multi_logloss: 0.136571
[400]	training's multi_logloss: 0.0249791	valid_1's multi_logloss: 0.114383
[500]	training's multi_logloss: 0.0128708	valid_1's multi_logloss: 0.10257
[600]	training's multi_logloss: 0.00701012	valid_1's multi_logloss: 0.0965033
[700]	training's multi_logloss: 0.00378853	valid_1's multi_logloss: 0.0929748
[800]	training's multi_logloss: 0.00223057	valid_1's multi_logloss: 0.0906518
[900]	training's multi_logloss: 0.0013276	valid_1's multi_logloss: 0.089515
[1000]	training's multi_logloss: 0.000839065	valid_1's multi_logloss: 0.0894826
[1100]	training's multi_logloss: 0.000544238	valid_1's multi_logloss: 0.0896533
Early stopping, best iteration is:
[938]	training's multi_logloss: 0.00110179	valid_1's multi_logloss: 0.0892531
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.261054	valid_1's multi_logloss: 0.315338
[200]	training's multi_logloss: 0.109111	valid_1's multi_logloss: 0.178008
[300]	training's multi_logloss: 0.0539501	valid_1's multi_logloss: 0.13394
[400]	training's multi_logloss: 0.0267479	valid_1's multi_logloss: 0.111574
[500]	training's multi_logloss: 0.0132579	valid_1's multi_logloss: 0.0993343
[600]	training's multi_logloss: 0.00715883	valid_1's multi_logloss: 0.0928242
[700]	training's multi_logloss: 0.00398709	valid_1's multi_logloss: 0.0888897
[800]	training's multi_logloss: 0.00212998	valid_1's multi_logloss: 0.0874413
[900]	training's multi_logloss: 0.00127542	valid_1's multi_logloss: 0.0870336
[1000]	training's multi_logloss: 0.000777189	valid_1's multi_logloss: 0.0871926
[1100]	training's multi_logloss: 0.00050519	valid_1's multi_logloss: 0.0880151
Early stopping, best iteration is:
[914]	training's multi_logloss: 0.00118193	valid_1's multi_logloss: 0.0868967
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.262655	valid_1's multi_logloss: 0.314301
[200]	training's multi_logloss: 0.113727	valid_1's multi_logloss: 0.177647
[300]	training's multi_logloss: 0.0544228	valid_1's multi_logloss: 0.131228
[400]	training's multi_logloss: 0.0259955	valid_1's multi_logloss: 0.108482
[500]	training's multi_logloss: 0.0126096	valid_1's multi_logloss: 0.0961747
[600]	training's multi_logloss: 0.0066178	valid_1's multi_logloss: 0.0897482
[700]	training's multi_logloss: 0.00406922	valid_1's multi_logloss: 0.0865705
[800]	training's multi_logloss: 0.00242108	valid_1's multi_logloss: 0.0849653
[900]	training's multi_logloss: 0.00148081	valid_1's multi_logloss: 0.0842584
[1000]	training's multi_logloss: 0.00091973	valid_1's multi_logloss: 0.0841904
[1100]	training's multi_logloss: 0.000640551	valid_1's multi_logloss: 0.0852207
Early stopping, best iteration is:
[911]	training's multi_logloss: 0.00139956	valid_1's multi_logloss: 0.0841523
Training until validation scores don't improve for 200 rounds.
[100]	training's multi_logloss: 0.261841	valid_1's multi_logloss: 0.313363
[200]	training's multi_logloss: 0.109556	valid_1's multi_logloss: 0.175142
[300]	training's multi_logloss: 0.0519981	valid_1's multi_logloss: 0.129784
[400]	training's multi_logloss: 0.0255247	valid_1's multi_logloss: 0.107945
[500]	training's multi_logloss: 0.0129249	valid_1's multi_logloss: 0.0965842
[600]	training's multi_logloss: 0.00672359	valid_1's multi_logloss: 0.0902928
[700]	training's multi_logloss: 0.00355253	valid_1's multi_logloss: 0.0866358
[800]	training's multi_logloss: 0.00199788	valid_1's multi_logloss: 0.0847112
[900]	training's multi_logloss: 0.0012154	valid_1's multi_logloss: 0.0848177
[1000]	training's multi_logloss: 0.000784775	valid_1's multi_logloss: 0.0843968
[1100]	training's multi_logloss: 0.000558327	valid_1's multi_logloss: 0.0852137
[1200]	training's multi_logloss: 0.000434195	valid_1's multi_logloss: 0.085915
Early stopping, best iteration is:
[1001]	training's multi_logloss: 0.000783114	valid_1's multi_logloss: 0.0843881

## Create submission file

In [ ]:
y_pred = y_pred.astype(int)
predict_df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Adopt a Buddy/Dataset/test.csv")
submit_df = pd.DataFrame()
submit_df['pet_id'] = predict_df['pet_id']
submit_df['pet_category'] = y_pred
submit_df['pet_category'] = submit_df['pet_category'].apply(lambda x: 4 if x==3 else x)
submit_df.head()

       pet_id  pet_category
0  ANSL_75005             2
1  ANSL_76663             1
2  ANSL_58259             2
3  ANSL_67171             2
4  ANSL_72871             2

In [ ]:
submit_df.to_csv("/content/drive/My Drive/Colab Notebooks/Adopt a Buddy/Predictions/predictions_v57_pc_LGB.csv", index=False)